### ISSUE TITLE
[BUG] - All cli commands require `--source` to be set

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#104]
All cli commands require the `--source` argument to be set.
This was not noticed until recently, as the argument will default to the env variable `PUNKTF_SOURCE` if not explicitly set.

```txt
  ==> Generating man page
  error: The following required arguments were not provided:
    --source <SOURCE>
  
  Usage: punktf --source <SOURCE> <COMMAND>
```

**Comment by michidk** [comment]
lol
