### ISSUE TITLE
[BUG] - File locations paths are weird on Windows

### ISSUE THREAD

**Issue by michidk** [Shemnei/punktf#137]
**Describe the bug**

This is the output upon deploying dotfiles succesfully on Windows:
```
PS C:\Users\michi> punktf deploy --source C:\Users\michi\dotfiles\ --profile windows --target C:\Users\michi\
Dotfiles (SUCCESS)
        \\?\C:\Users\michi\.ssh\config
        \\?\C:\Users\michi
        \\?\C:\Users\michi\.gitconfig
        \\?\C:\Users\michi\.ssh
Status: SUCCESS
Time            : 1.2227ms
--------------------------------------------------------------------------------
Files (deployed): 4
Files (skipped) : 0
Files (failed)  : 0
Files (total)   : 4
--------------------------------------------------------------------------------
Links (deployed): 0
Links (skipped) : 0
Links (failed)  : 0
Links (total)   : 0
```

**To Reproduce**

Run most recent `punktf` release on Windows.

**Expected behavior**

`\\?\C:\Users\michi\.ssh\config` is incorrect and should be `C:\Users\michi\.ssh\config` instead

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: punktf 3.1.0

**Comment by Shemnei** [comment]
Windows 🤷
This is the "full" path representation using UNC (i think `\\?` represents a root local device) (<https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html>).
I would not say it's a but, but should probably be adjusted for display purposes.

**Comment by michidk** [comment]
It's definitely a bug or was it by intention?
