### ISSUE TITLE
Check Command

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#19]
Checks for:

- Item required by a profile but is missing
- Invalid templates
- Items which are not referenced anywhere (no profile requires them)

**Comment by michidk** [comment]
Do we really want this for 1.0.0?

**Comment by Shemnei** [comment]
Probably not, as we already have a crude way to check (with `deploy --dry-run`). I am fine with moving it back.

**Comment by Shemnei** [comment]
Will be implemented as the `verify` subcommand
