### ISSUE TITLE
Setup Github repo

### ISSUE THREAD

**Issue by michidk** [Shemnei/punktf#2]
Set the following description:
`⚡ A cross-platform multi-target dotfiles manager`

Add the following tags:
`rust`, `dotfiles`, `cli`, `dotfile`, `dotfile-manager`

**Comment by Shemnei** [comment]
Done

**Comment by michidk** [comment]
The awesome ⚡ emote is missing :c

**Comment by michidk** [comment]
All cool tools need emotes

**Comment by Shemnei** [comment]
I hate emojis for code. But i will accept that one if you swear to never use an emoji in a commit message.

**Comment by michidk** [comment]
🥳 I hereby promise to try not to use emoticons in commit messages in this repository.

**Comment by michidk** [comment]
Also readme files and code non-functional documentation are not code! 😁

**Comment by Shemnei** [comment]
Ok ...
