### ISSUE TITLE
Group deployable items by priority and deploy in order

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#27]
Before starting the deployment, group all items by priority. Then deploy in sorted order (highest first). This allows for specilization of single items (when used together with generic directory deploy) and can reduce disk read/writes.

**Comment by michidk** [comment]
Do we want this in v1 already?

**Comment by Shemnei** [comment]
I hope that it is not too much work. If it is too much we probably should push it back.
Its a necessary step before we can think about multitasking (e.g. #29).

**Comment by Shemnei** [comment]
Maybe you are right and we should push it back. We probably also want to sort by merge operation inside the same priority. And have to think about the multitasking model.
