### ISSUE TITLE
Parallelize templating process

### ISSUE THREAD

**Issue by michidk** [Shemnei/punktf#29]
Similar to https://github.com/sharkdp/fd/blob/master/src/exec/job.rs

**Comment by Shemnei** [comment]
I think we can push this one back for a while.
My personal setup with around 71 files (a majority is marked as template) only takes around 17ms.
I have to admit i have decent hardware but even on lower end pcs i would suspect this would not be a problem.

If the deploy times reach around 500ms-1s we should think about this again.

**Comment by Shemnei** [comment]
I will close this for now for the reasons mentioned in the previous comment (deploy times are currently rather short).
