### ISSUE TITLE
Add cli option to output Deployment to file

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#47]
Add a cli option (e.g. `--output-json`) to export the created Deployment to a file/stream

**Comment by Shemnei** [comment]
The final deployment result can be written to a file with the cli arguments `--json-output/--yaml-output`

**Comment by michidk** [comment]
What is the usecase for this?

**Comment by Shemnei** [comment]
This would make the deployment status machine readable which might be usefull in some kind of automation / testing / pipeline scenarios.
