### ISSUE TITLE
Add Resolver for (Dotfile/Profile)::target

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#48]
Resolve stuff like `~` and maybe environment variables like `$HOME` when evaluating the profile and dotfile target.

**Comment by Shemnei** [comment]
All final target and source paths of the profile will now be "resolved".
This includes:

- Dotfile.path
- Dotfile.rename
- Dotfile.overwrite_target
- Links.source_path
- Links.target_path

The following things will be resolved/replaced:

- A `~` if it occurs at the start of the path (e.g. `~/.config`) => Will be replaced by the user home directory (see [home_dir](https://docs.rs/home/latest/home/fn.home_dir.html) for more info)
- A path segment which starts with `$` (e.g. `/test/$EDITOR/config.ini`) => Will be replaced by the environment variable
- A path segment which is enclosed by `%` and `%` (e.g. `%APPDATA%\neovim`) => Will be replaced by the environment variable

**Comment by michidk** [comment]
This crates implements something similar: https://crates.io/crates/shellexpand

**Comment by Shemnei** [comment]
I was looking for something like that but did not find anything.
This crate is almost exactly what i wanted, so thanks for the suggestion.
I replaced the hand rolled version with the crate.
