### ISSUE TITLE
Skip dotfile deployment if hash matches

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#50]
This will prevent some write operations as well as skip some unnecessary user merge ask function calls.

**Comment by michidk** [comment]
Calculating a hash from the whole file can become expensive if it's large. Maybe add a flag to the config, so that hashes can be disabled for specific files.

**Comment by Shemnei** [comment]
If we use something like `md5` the time cost should not be that high altough you are right it will probably accumulate when processing many files. You make a good point with the flag and the flag will defenetly be implemented but probably as a `all or nothing` kind of thing.

**Comment by Shemnei** [comment]
I will be closing this as i now think you are right @michidk, the overhead is not worth it for the kind of files `punktf` is meant to work with.
