### ISSUE TITLE
Improve wiki (Profile + Example Template)

### ISSUE THREAD

**Issue by Shemnei** [Shemnei/punktf#63]

**Comment by Shemnei** [comment]
Maybe instead of using the github wiki we could switch to [`mdBook`](https://github.com/rust-lang/mdBook).
This then could be hosted on github pages.

**Comment by michidk** [comment]
What are the advantages?

**Comment by Shemnei** [comment]
There are multiple:

- Anybody can propose a PR for wiki changes
- It is independent of github (making migration to other platforms easier) (yes i know github wiki is a git repo, but it has special md extensions / structure; mdbook is the same everywhere)
- Changes to the wiki can be done on a different branch and only be merged when to actual change go live  (had the problem with the `more-commands` branch; wanted to document the new features but not make them public/live on github wiki). With this the wiki is in the same gitrepo and can be adjusted in the pr.
- It is a rust project 😄 
- It can be used as a base for a website (currently auto deploying to github pages)

**Comment by michidk** [comment]
I like it :)

**Comment by Shemnei** [comment]
That only leaves the daunting task of transferring everything from the github wiki to mdbook and also expanding it 😅
